#!/bin/sh
export QEMU_AUDIO_DRV=alsa

#-device virtio-serial -chardev spicevmc,id=vdagent,debug=0,name=vdagent \
#-device virtserialport,chardev=vdagent,name=com.redhat.spice.0 \
#-spice port=7100,disable-ticketing \

kvm -name Linux \
	-drive if=virtio,file=/home/debbuilder/lxde.qcow2,media=disk,cache=unsafe \
	-boot order=d \
	-cpu host \
	-m 1024 \
	-usbdevice tablet \
	-vga qxl \
	-spice port=7120,disable-ticketing \
	-net nic,model=virtio \
	-net user \
	-cdrom  /home/debbuilder/iso-nox-amd64/siduction-12.2.0-ridersonthestorm-nox-amd64-201303042242.iso \

# Nach Beenden der KVM, Interface stoppen und entfernen
#sudo /sbin/ifconfig $INTERFACE down
#sudo /usr/sbin/tunctl -d $INTERFACE &> /dev/null
#reset
