#!/bin/bash

## defaults
options="-v " 
confpath="./pyfll/conf/"
flavour=kde
release=next
arch=amd64
aptcache="-t http://192.168.150.41:3142"

time ./pyfll/fll ${options}  ${aptcache} -c ${confpath}${flavour}_${release}_${arch}.conf 
