#!/bin/sh

# Copyright © 2017 Alf Gaida <agaida@siduction.org>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See the COPYING file or http://www.wtfpl.net/
# for more details.

gpg --export --armor $1 | apt-key add -
