#!/bin/bash

# one will find a sample defaults.conf in ./pyfll
[ -e /etc/pyfll/defaults.conf ] && source /etc/pyfll/defaults.conf

flavour=lxde
release=farwell
arch=amd64

time ./pyfll/fll ${options}  ${aptcache} -c ${confpath}${flavour}_${release}_${arch}.conf
